"""M11: the Seed's files and the approved Seed (FR-F-1 to FR-F-5, FR-R-4, AC-4, AC-5, D-72 to D-75).

Golden files for both approval paths: iteration 2 approved has learned rules and no known issues;
iteration 1 approved has every open finding as a known issue in each file and no learned rules. The
templates: header block, build-simulation.md §7's sections in order, the observer feedback in the
layer its section belongs to, learned rules from the data, no intake file named. Over HTTP: Approve,
each file and the zip, the zip byte for byte and the same twice, the refusals, Reset, determinism and
a restart.
"""

from __future__ import annotations

import io
import json
import zipfile

import pytest
from fastapi.testclient import TestClient

from report_fixtures import sample_builds
from seed_fixtures import PATHS, approved_state, fixtures
from seedfoundry import package, report
from seedfoundry.engine.clock import FakeClock
from seedfoundry.engine.runner import SLICE
from seedfoundry.generate import layers
from seedfoundry.intake import assay
from seedfoundry.intake.feedback import feedback_file, segments
from seedfoundry.main import create_app
from seedfoundry.sample import demo_feedback, sample_files
from seedfoundry.state import Category, IntakeFile

CATALOGUE = ["N-1", "N-2", "N-3", "N-4", "N-5", "V-1", "V-2", "V-3", "V-4", "V-5", "V-6", "V-7", "V-8", "L-1"]
INTAKE_NAMES = ("person.md", "instrument-awareness.md", "environment.md", "music.md", "vendor-notes.md", "player.md")
# The initiation files' names and screen names since D-84 and D-85.
INTAKE_NAMES += ("Identity.md", "Tools_and_Skills.md", "Environment_01.md", "Environment_02.md", "Value_0001.md", "Value_0002.md")
# The categories' screen names: no Seed file holds them, but the Seed page's test names may (T-04,
# "All Value.md sections extracted"), as they named "Music" before (D-84).
SCREEN_NAMES = ("Environment.md", "Value.md")
SECTIONS = {
    "core.md": ["Purpose", "Core principles", "Value logic", "Decision rules", "Reasoning approach", "Execution guidance"],
    "adaptation.md": ["Operating context", "Data sources and mappings", "Account and industry adjustments", "Presentation notes"],
    "protection.md": ["Guardrails", "Validation checks", "Quality controls", "Security"],
}


def h2(text: str) -> list[str]:
    return [s.title for s in assay.sections(text) if s.level == 2]


def section(text: str, title: str, level: int = 2) -> str:
    return "\n".join(assay.section_lines(text, title, level) or [])


@pytest.fixture(scope="module")
def paths() -> dict[int, dict[str, str]]:
    return {iteration: package.seed_files(*package.approved(approved_state(iteration))) for iteration in PATHS}


# Golden files (both approval paths)


@pytest.mark.parametrize("path", sorted(fixtures(), key=str), ids=lambda p: f"{p.parent.name}/{p.name}")
def test_the_golden_files_and_page_fixtures_are_what_the_backend_makes(path):
    assert path.exists(), f"run: uv run python tests/seed_fixtures.py ({path.name} is missing)"
    assert path.read_text(encoding="utf-8") == fixtures()[path], f"{path.name} is stale: run uv run python tests/seed_fixtures.py"


@pytest.mark.parametrize("iteration", PATHS)
def test_each_file_starts_with_the_header_block_then_has_section_7s_sections_in_order(paths, iteration):
    for name, text in paths[iteration].items():
        assert text.split("\n")[:6] == [
            f"# License Optimization: {name}",
            "",
            "- Seed: License Optimization",
            f"- Iteration: {iteration}",
            f"- Intake fingerprint: {sample_builds()[iteration - 1].fingerprint}",
            "- Generated by SeedFactory",
        ]
        expected = SECTIONS[name] + (["Learned rules"] if name == "protection.md" and iteration == 2 else [])
        assert h2(text) == expected + (["Known issues"] if iteration == 1 else [])
        assert layers.NOTHING not in text  # the sample states every section
        assert text.endswith("\n") and not text.endswith("\n\n")


def test_iteration_2_approved_has_learned_rules_and_no_known_issues(paths):
    two = paths[2]
    assert all("## Known issues" not in text for text in two.values())
    rules = section(two["protection.md"], "Learned rules")
    assert [s.title for s in assay.sections(rules) if s.level == 3] == ["Numeric", "Visual", "Latency"]
    assert "Every part-to-whole chart must reconcile to its total." in rules
    # Each rule cites exactly the iteration 1 findings of its class.
    for category, ids in (("Numeric", CATALOGUE[:5]), ("Visual", CATALOGUE[5:13]), ("Latency", ["L-1"])):
        cited = section(rules, category, 3).split("Learned from", 1)[1]
        assert [i for i in CATALOGUE if f"{i} (" in cited] == ids


def test_iteration_1_approved_lists_every_open_finding_in_each_file_and_has_no_learned_rules(paths):
    first, _ = sample_builds()
    ids = [f["id"] for f in report.raised(first)]
    assert ids == CATALOGUE
    for name, text in paths[1].items():
        issues = section(text, "Known issues")
        assert issues.strip().startswith("Approved at iteration 1 with 14 open findings.")
        assert [line.split("**")[1] for line in issues.split("\n") if line.startswith("- **")] == ids, name
        assert "## Learned rules" not in text


def test_the_learned_rules_line_in_synthesis_names_the_classes_the_file_has(paths):
    _, second = sample_builds()
    line = next(e for e in second.log if e.type == "log" and e.message.startswith("Learned rules for protection.md"))
    rules = section(paths[2]["protection.md"], "Learned rules")
    assert sorted(line.data["classes"]) == sorted(s.title for s in assay.sections(rules) if s.level == 3)


def test_which_rules_are_learned_comes_from_the_findings_not_a_list():
    files = intake()
    only_latency = [{"id": "L-1", "category": "Latency", "panel_titles": ["A panel"]}]
    text = layers.drafts(files, "S", 2, "abc123", only_latency)["protection.md"]
    assert [s.title for s in assay.sections(section(text, "Learned rules")) if s.level == 3] == ["Latency"]
    unknown = [{"id": "Q-1", "category": "Quirky", "panel_titles": []}, {"id": "B-DATA-1", "category": "Boundary", "advisory": True}]
    text = layers.drafts(files, "S", 2, "abc123", unknown)["protection.md"]
    assert [s.title for s in assay.sections(section(text, "Learned rules")) if s.level == 3] == ["Quirky"]
    assert "Iteration 1 raised no findings" in layers.drafts(files, "S", 2, "abc123", [])["protection.md"]
    assert "## Learned rules" not in layers.drafts(files, "S", 1, "abc123", only_latency)["protection.md"]


def test_approved_iteration_2_files_are_the_layers_the_build_planted_byte_for_byte(paths):
    for iteration in PATHS:
        build = sample_builds()[iteration - 1]
        uploads = {e.data["path"].rsplit("/", 1)[-1]: e.data for e in build.log if e.type == "api.call" and e.step == "contain.upload"}
        manifest = next(e.data["manifest"] for e in build.log if e.step == "synth.manifest" and e.type == "log")
        for name, text in paths[iteration].items():
            planted = text.split("\n## Known issues\n")[0].rstrip("\n") + "\n" if iteration == 1 else text
            layer = next(item for item in manifest["layers"] if item["name"] == name)
            assert (layer["sha256"], layer["bytes"]) == (package.digest(planted), len(planted.encode("utf-8")))
            assert uploads[name]["response"]["sha256"] == package.digest(planted)


def test_synthesis_and_package_lines_read_the_full_files(paths):
    _, second = sample_builds()
    lines = {
        e.step: e.message
        for e in second.log
        if e.type == "log" and (e.step == "report.package" or ((e.step or "").startswith("synth.") and e.message.startswith("Drafted")))
    }
    for name in layers.NAMES:
        size = len(paths[2][name].encode("utf-8"))
        assert lines[f"synth.{name.removesuffix('.md')}"] == f"Drafted {name}: {len(h2(paths[2][name]))} sections, {size:,} bytes"
        assert f"{name} ({size:,} bytes)" in lines["report.package"]
    assert "Approve offers them one by one and as one zip" in lines["report.package"]
    assert "arrive" not in lines["report.package"] and "outline" not in " ".join(lines.values())


# What goes where (project-notes.md §4), and what is never said (D-9)

# Where each routed section's text lands in the Seed.
HOME = {
    ("Environment_01.md", "Data Layer"): ("adaptation.md", "Data sources and mappings"),
    ("Environment_01.md", "Styling"): ("adaptation.md", "Presentation notes"),
    ("Environment_01.md", "User Experience"): ("adaptation.md", "Presentation notes"),
    ("Environment_01.md", "Protection Layer"): ("protection.md", "Guardrails"),
    ("Tools_and_Skills.md", "Model Behaviour"): ("core.md", "Execution guidance"),
    ("Identity.md", "Reasoning methods"): ("core.md", "Reasoning approach"),
    ("Value_0001.md", "Value Logic"): ("core.md", "Value logic"),
    ("Value_0001.md", "Core Principles"): ("core.md", "Core principles"),
    ("Value_0001.md", "Decision Logic"): ("core.md", "Decision rules"),
}


def test_the_observer_feedback_sections_feed_the_layers_they_belong_to(paths):
    _, second = sample_builds()
    parts = segments(feedback_file(second.files).content)
    updates = report.assemble(second, sample_builds()[0])["changes"]["updates"]
    assert updates
    for update in updates:
        name, title = HOME[(update["file"], update["section"])]
        body = section(paths[2][name], title)
        assert "Observer feedback (iteration 1)" in body
        for number in update["segments"]:
            assert parts[number - 1] in body, (update, number)


def test_no_file_names_an_intake_file_or_says_what_it_came_from(paths):
    for iteration in PATHS:
        for name, text in paths[iteration].items():
            for intake_name in INTAKE_NAMES + SCREEN_NAMES:
                assert intake_name not in text, (iteration, name, intake_name)
            assert "Ensemble" not in text and "Knowledge" not in text
    # The sample's mention ("as Value.md defines them") reads as the layer that holds the text now.
    # Its second mention went with the vendor notes (D-84).
    assert "as core.md defines them" in paths[2]["adaptation.md"]


def test_the_page_data_names_no_intake_file():
    # The history's feedback is the observer's own text, quoted; the demo's names no file either.
    for iteration in PATHS:
        text = json.dumps(package.page(approved_state(iteration)), ensure_ascii=False)
        for intake_name in INTAKE_NAMES:
            assert intake_name not in text


# The templates on other intake


def intake(**overrides: str) -> list[IntakeFile]:
    files = [IntakeFile(id=f"f-{i}", name=name, category=category, content=content) for i, (name, category, content) in enumerate(sample_files())]
    for name, content in overrides.items():
        files = [f.model_copy(update={"content": content}) if f.category.value == name else f for f in files]  # by category (D-85)
    return files


def test_a_missing_section_says_so_and_headings_move_under_the_layer():
    music = "# Seed X\n\nA lead.\n\n## Purpose\n\nDo the thing.\n\n```\n## not a heading\n```\n"
    environment = (
        "# Env\n\n## Protection Layer\n\nTop rule.\n\n### Access control\n\n- Only staff.\n\n#### Detail\n\nDeep.\n\n"
        "### Reconciliation\n\n- Sums agree.\n\n### Something else\n\n- Kept.\n"
    )
    made = layers.drafts(intake(music=music, environment=environment), "Seed X", 1, "abc123")
    core, protection = made["core.md"], made["protection.md"]
    assert h2(core) == SECTIONS["core.md"]
    assert section(core, "Core principles").strip() == layers.NOTHING
    assert "```\n## not a heading\n```" in core
    assert section(core, "Purpose").strip().startswith("A lead.")
    # Each Protection Layer sub-section goes under the section its title names, guardrails otherwise.
    assert "- Only staff." in section(protection, "Security") and "### Detail" in section(protection, "Security")
    assert "- Sums agree." in section(protection, "Validation checks")
    assert "Top rule." in section(protection, "Guardrails") and "- Kept." in section(protection, "Guardrails")
    assert section(protection, "Quality controls").strip() == layers.NOTHING
    assert "Nothing is stated" in section(made["adaptation.md"], "Data sources and mappings")


def test_the_same_intake_gives_the_same_bytes():
    first, second = layers.drafts(intake(), "S", 1, "abc123"), layers.drafts(intake(), "S", 1, "abc123")
    assert first == second


# Approve, downloads and the zip over HTTP (FR-F-1, FR-F-3, AC-4, AC-5)


@pytest.fixture
def clock() -> FakeClock:
    return FakeClock(auto=False)


@pytest.fixture
def api(var_dir, clock):
    with TestClient(create_app(var_dir, clock)) as client:
        yield client


def finish(client: TestClient, clock: FakeClock) -> None:
    assert client.post("/api/demo/skip", json={"to": "build"}).status_code == 200
    client.portal.call(clock.advance, SLICE)
    client.portal.call(client.app.state.engine.wait)


def first_iteration(client: TestClient, clock: FakeClock) -> None:
    assert client.post("/api/demo/sample", json={}).status_code == 201
    assert client.post("/api/builds", json={}).status_code == 201
    finish(client, clock)


def two_iterations(client: TestClient, clock: FakeClock) -> None:
    first_iteration(client, clock)
    assert client.post("/api/builds", json={"iteration": 2, "feedback": demo_feedback()}).status_code == 201
    finish(client, clock)


def approve(client: TestClient, build_id: str):
    return client.post("/api/seed/approve", json={"build_id": build_id})


def downloads(client: TestClient) -> tuple[dict[str, bytes], bytes]:
    return {name: client.get(f"/api/seed/files/{name}").content for name in layers.NAMES}, client.get("/api/seed/zip").content


def test_approving_iteration_2_records_it_and_serves_the_seed(api, clock, paths):
    two_iterations(api, clock)
    seq = api.app.state.lab.state.seq
    response = approve(api, "b-2")
    assert response.status_code == 201
    page = response.json()
    assert api.get("/api/seed").json() == page
    assert {k: page["approval"][k] for k in ("iteration", "build_id")} == {"iteration": 2, "build_id": "b-2"}
    assert page["approval"]["approved_at"]
    assert api.get("/api/state").json()["approval"]["build_id"] == "b-2"
    assert page["known_issues"] == []
    assert [f["name"] for f in page["files"]] == list(layers.NAMES)
    assert {f["name"]: f["content"] for f in page["files"]} == paths[2]
    # One event, outside any build, so no build's console shows it.
    [event] = api.app.state.lab.log.after(seq)
    assert (event.type, event.build_id, event.data["known_issues"]) == ("seed.approved", None, [])
    assert event.message == 'Seed approved: "License Optimization", iteration 2; 3 files, no known issues'


def test_each_file_and_the_zip_download_and_the_zip_holds_exactly_the_three_files(api, clock, paths):
    two_iterations(api, clock)
    approve(api, "b-2")
    for name in layers.NAMES:
        response = api.get(f"/api/seed/files/{name}")
        assert response.status_code == 200
        assert response.headers["content-type"] == "text/markdown; charset=utf-8"
        assert response.headers["content-disposition"] == f'attachment; filename="{name}"'
        assert response.content == paths[2][name].encode("utf-8")
    response = api.get("/api/seed/zip")
    assert response.headers["content-type"] == "application/zip"
    assert response.headers["content-disposition"] == 'attachment; filename="license-optimization-seed.zip"'
    archive = zipfile.ZipFile(io.BytesIO(response.content))
    assert archive.namelist() == list(layers.NAMES)
    files, _ = downloads(api)
    for info in archive.infolist():
        assert archive.read(info) == files[info.filename]
        assert info.date_time == package.ZIP_TIME
    assert api.get("/api/seed").json()["zip"]["bytes"] == len(response.content)
    assert api.get("/api/seed/zip").content == response.content


def test_approving_iteration_1_lists_every_open_finding_on_the_page_and_in_each_file(api, clock, paths):
    first_iteration(api, clock)
    page = approve(api, "b-1").json()
    assert [f["id"] for f in page["known_issues"]] == CATALOGUE
    assert [h["kind"] for h in page["history"]] == ["iteration"]
    files, zipped = downloads(api)
    assert {n: c.decode("utf-8") for n, c in files.items()} == paths[1]
    assert all(b"## Known issues" in c and b"## Learned rules" not in c for c in files.values())
    assert zipfile.ZipFile(io.BytesIO(zipped)).read("core.md") == files["core.md"]


def test_the_page_data_for_iteration_2(api, clock):
    two_iterations(api, clock)
    page = approve(api, "b-2").json()
    assert page["purpose"]["from"] == "purpose" and page["purpose"]["text"].startswith("- Find the seats")
    assert (page["verdict"]["label"], page["counts"]["tests"], page["counts"]["pass"]) == ("Passed", 21, 21)
    assert [p["name"] for p in page["phases"]][0] == "Assay" and len(page["phases"]) == 11
    assert [t["id"] for p in page["phases"] for t in p["tests"]] == [f"T-{n:02d}" for n in range(1, 22)]
    one, feedback, two = page["history"]
    assert (one["iteration"], one["findings"], one["approved"]) == (1, 14, False)
    assert (feedback["kind"], feedback["content"], feedback["segments"], feedback["routed"], feedback["files_updated"]) == ("feedback", demo_feedback(), 10, 9, 4)
    assert (two["iteration"], two["findings"], two["resolved"], two["prior_findings"], two["approved"]) == (2, 0, 14, 14, True)
    assert [f["bytes"] for f in page["files"]] == [len(f["content"].encode("utf-8")) for f in page["files"]]
    assert "rules learned from iteration 1" in page["files"][2]["description"]


def test_the_purpose_falls_back_to_the_first_paragraph():
    files = intake(music="# Seed X\n\nCut licence spend.\nKeep tools people need.\n\n## Core Principles\n\n- One.\n")
    assert package.purpose(files) == {"from": "first_paragraph", "text": "Cut licence spend.\nKeep tools people need."}
    assert package.purpose(intake(music="# Only a title\n")) == {"from": "none", "text": ""}


def test_refusals(api, clock):
    assert api.get("/api/seed").json()["detail"]["code"] == "seed_not_approved"
    assert api.get("/api/seed/files/core.md").status_code == 404
    assert api.get("/api/seed/zip").status_code == 404
    assert approve(api, "b-9").json()["detail"]["code"] == "build_not_found"
    assert api.post("/api/demo/sample", json={}).status_code == 201
    assert api.post("/api/builds", json={}).status_code == 201
    running = approve(api, "b-1")
    assert (running.status_code, running.json()["detail"]["code"]) == (409, "build_running")
    finish(api, clock)
    assert api.post("/api/builds", json={"iteration": 2, "feedback": demo_feedback()}).status_code == 201
    finish(api, clock)
    # Iteration 1 cannot be approved once iteration 2 has started (D-73).
    superseded = approve(api, "b-1")
    assert (superseded.status_code, superseded.json()["detail"]["code"]) == (409, "iteration_superseded")
    assert api.app.state.lab.state.approval is None
    assert approve(api, "b-2").status_code == 201
    again = approve(api, "b-2")
    assert (again.status_code, again.json()["detail"]["code"]) == (409, "seed_approved")
    # A build after approval is refused (D-49).
    build = api.post("/api/builds", json={})
    assert (build.status_code, build.json()["detail"]["code"]) == (409, "seed_approved")
    assert api.get("/api/seed/files/manifest.json").json()["detail"]["code"] == "seed_file_not_found"


def test_a_running_build_cannot_be_approved_before_it_completes(api, clock):
    assert api.post("/api/demo/sample", json={}).status_code == 201
    assert api.post("/api/builds", json={}).status_code == 201
    assert api.app.state.lab.state.build("b-1").status == "running"
    assert approve(api, "b-1").json()["detail"]["code"] == "build_running"


def test_reset_clears_the_approval(api, clock):
    first_iteration(api, clock)
    assert approve(api, "b-1").status_code == 201
    assert api.post("/api/demo/reset").status_code == 200
    assert api.get("/api/state").json()["approval"] is None
    assert api.get("/api/seed").status_code == 404
    first_iteration(api, clock)  # building is allowed again
    assert approve(api, "b-2").status_code == 201


# Determinism (NFR-1) and a restart


def test_the_same_approval_twice_gives_the_same_files_zip_page_and_events(tmp_path):
    runs = []
    for name in ("one", "two"):
        clock = FakeClock(auto=False)
        with TestClient(create_app(tmp_path / name, clock)) as client:
            two_iterations(client, clock)
            page = approve(client, "b-2").json()
            page["approval"].pop("approved_at")
            events = [{k: v for k, v in e.model_dump(mode="json").items() if k != "wall_ts"} for e in client.app.state.lab.log.after(0)]
            runs.append((downloads(client), page, events))
    assert runs[0] == runs[1]


def test_downloads_survive_a_restart(var_dir):
    clock = FakeClock(auto=False)
    with TestClient(create_app(var_dir, clock)) as client:
        first_iteration(client, clock)
        approve(client, "b-1")
        before = (downloads(client), client.get("/api/seed").json())
    with TestClient(create_app(var_dir)) as client:
        assert (downloads(client), client.get("/api/seed").json()) == before


def test_the_zip_is_the_same_bytes_for_the_same_files():
    made = package.seed_files(*package.approved(approved_state(2)))
    assert package.zip_bytes(made) == package.zip_bytes(dict(made))
    assert package.zip_name("License Optimization") == "license-optimization-seed.zip"
    assert package.zip_name("!!") == "seed-seed.zip"


def test_a_core_file_named_otherwise_is_still_rewritten():
    files = [f.model_copy(update={"name": "player.md"}) if f.category == Category.PERSON else f for f in intake()]
    files = [f.model_copy(update={"content": f.content + "\n- See player.md.\n"}) if f.category == Category.MUSIC else f for f in files]
    made = layers.drafts(files, "S", 1, "abc123")
    assert "- See core.md." in made["core.md"] and "player.md" not in "".join(made.values())
