"""The Seed's three layers, core.md, adaptation.md and protection.md (FR-F-5, build-simulation.md §7,
D-72): real, deterministic templates over the distilled intake, with no LLM.

Each file starts with the header block (Seed name, iteration, intake fingerprint, "Generated by
SeedFoundry"), then one line saying what the layer is, then §7's sections in order. What goes where
follows project-notes.md §4, which drives generation and is never written into a file or shown on a
screen (D-9):

- core.md: music.md's lead and Purpose, its Core Principles, Value Logic and Decision Logic; person.md
  as the reasoning approach; instrument-awareness.md as the execution guidance.
- adaptation.md: environment.md's lead and the Misc Context notes as the operating context; its Data
  Layer; its Adaptation Layer; its User Experience and Styling as the presentation notes.
- protection.md: environment.md's Protection Layer, each sub-section under the section its title
  names (guardrails otherwise); in iteration 2, one learned rule per class of finding iteration 1
  raised, from iteration 1's kept findings.

Iteration 2 reads the routed files build 2 keeps, so each `### Observer feedback (iteration 1)` sits
in the layer its section belongs to. Text is copied as written; only its headings move to fit under
the layer's sections, and a mention of an intake file by name becomes the layer or note that now
holds it, so the Seed reads as one whole. Synthesis drafts all three in the build, so the manifest,
the upload checksums and Planting's heading summary are computed from these bytes; Approve adds the
Known issues section when the approved build has findings (D-73).
"""

from __future__ import annotations

import hashlib
import re
from dataclasses import dataclass, field
from typing import Any

from seedfoundry.intake import assay
from seedfoundry.intake.feedback import FEEDBACK_NAME
from seedfoundry.state import Category, IntakeFile
from seedfoundry.validators.findings import order
from seedfoundry.validators.latency import BUDGET_MS


@dataclass(frozen=True)
class Layer:
    name: str
    role: str
    title: str
    description: str
    sections: tuple[str, ...]


LAYERS: tuple[Layer, ...] = (
    Layer(
        "core.md",
        "core",
        "Core",
        "what this Seed is for, what it values, and how it decides, reasons and works.",
        ("Purpose", "Core principles", "Value logic", "Decision rules", "Reasoning approach", "Execution guidance"),
    ),
    Layer(
        "adaptation.md",
        "adaptation",
        "Adaptation",
        "where this Seed runs, the data it reads, how it fits this account and how its output is presented.",
        ("Operating context", "Data sources and mappings", "Account and industry adjustments", "Presentation notes"),
    ),
    Layer(
        "protection.md",
        "protection",
        "Protection",
        "the guardrails, checks and controls that keep this Seed safe and its output correct.",
        ("Guardrails", "Validation checks", "Quality controls", "Security"),
    ),
)
NAMES = tuple(layer.name for layer in LAYERS)

LEARNED_RULES = "Learned rules"  # protection.md, iteration 2 only
KNOWN_ISSUES = "Known issues"  # every file, when the approved build has findings (D-10, D-73)
NOTHING = "Nothing is stated for this section."

# One rule per class of finding (build-simulation.md §7). Which classes appear comes from the findings
# iteration 1 raised; a class with no wording here still gets a rule.
RULES = {
    "Numeric": (
        "Every part-to-whole chart must reconcile to its total. Recompute every figure from the records before it is "
        "shown: parts sum to their totals, shares sum to 100%, a derived figure equals its formula, and one measure "
        "agrees on every panel where it appears."
    ),
    "Visual": (
        "Every chart must keep to the design system. Colours come from the palette, with red for faults only; a chart "
        "type fits its data, with no pie of more than six slices; each measure keeps one number format, with its unit "
        "and named axes; cards sit on the grid, in one font per role; text meets AA contrast in both themes."
    ),
    "Latency": (
        f"Every panel must render within its {BUDGET_MS / 1000:.1f} s budget. A slower panel is a finding, not a "
        "loading state to wait out."
    ),
}

_HEADING = re.compile(r"^(#{1,6})\s+(.+?)\s*#*\s*$")
_FENCE = re.compile(r"^\s*(```|~~~)")


def layer(name: str) -> Layer:
    return next(item for item in LAYERS if item.name == name)


def sections(name: str, iteration: int, known_issues: bool = False) -> tuple[str, ...]:
    found = layer(name).sections
    if layer(name).role == "protection" and iteration == 2:
        found += (LEARNED_RULES,)
    return found + (KNOWN_ISSUES,) if known_issues else found


def description(name: str, iteration: int) -> str:
    """One line on what the layer holds, for the file and the Seed page's cards (never which intake
    file it came from, D-9)."""
    item = layer(name)
    text = f"{item.title} layer: {item.description}"
    return text + " It also holds the rules learned from iteration 1." if item.role == "protection" and iteration == 2 else text


# Reading the intake


@dataclass
class Part:
    """A heading and its lines, sub-headings included."""

    title: str
    level: int
    lines: list[str] = field(default_factory=list)


def heading(line: str) -> tuple[int, str] | None:
    match = _HEADING.match(line)
    return (len(match.group(1)), match.group(2).strip()) if match else None


def split(lines: list[str], level: int) -> tuple[list[str], list[Part]]:
    """Lines cut at headings of `level` (or above): the lines before the first, then each part.
    Lines in a code fence are never headings."""
    intro: list[str] = []
    parts: list[Part] = []
    fenced = False
    for line in lines:
        if _FENCE.match(line):
            fenced = not fenced
        found = None if fenced else heading(line)
        if found and found[0] <= level:
            parts.append(Part(found[1], found[0]))
        elif parts:
            parts[-1].lines.append(line)
        else:
            intro.append(line)
    return intro, parts


def shift(lines: list[str], by: int) -> list[str]:
    """Every heading `by` levels deeper (or shallower), outside code fences."""
    out: list[str] = []
    fenced = False
    for line in lines:
        if _FENCE.match(line):
            fenced = not fenced
        found = None if fenced or not by else heading(line)
        out.append(f"{'#' * min(max(found[0] + by, 1), 6)} {found[1]}" if found else line)
    return out


def trim(lines: list[str]) -> list[str]:
    start, end = 0, len(lines)
    while start < end and not lines[start].strip():
        start += 1
    while end > start and not lines[end - 1].strip():
        end -= 1
    return lines[start:end]


def combined(parts: list[Part], top: int = 2) -> list[str]:
    """Parts under one `top` heading: a single part's lines with its sub-headings one level below the
    top, or several, each under its own heading one level below."""
    if len(parts) == 1:
        return trim(shift(parts[0].lines, top - parts[0].level))
    out: list[str] = []
    for part in parts:
        out += ["", f"{'#' * (top + 1)} {part.title}", "", *trim(shift(part.lines, top + 1 - part.level))]
    return trim(out)


@dataclass
class Document:
    """One intake file cut into its lead (the text under its title) and its `##` sections."""

    file: IntakeFile
    lead: list[str]
    parts: list[Part]

    @classmethod
    def read(cls, file: IntakeFile, text: str) -> Document:
        intro, parts = split(text.split("\n"), 2)
        # The lead is the text before the first `##`, under the file's `#` title if it has one.
        lead = intro + (parts[0].lines if parts and parts[0].level == 1 else [])
        return cls(file, trim(lead), [p for p in parts if p.level == 2])

    def part(self, title: str) -> Part | None:
        return next((p for p in self.parts if assay.key(p.title) == assay.key(title)), None)

    def body(self, title: str) -> list[str]:
        found = self.part(title)
        return combined([found]) if found else []


class Source:
    """The intake a build read: the four core files and the Misc Context notes (the observer
    feedback aside: what it changed is already in the core files)."""

    def __init__(self, files: list[IntakeFile]) -> None:
        inventory = assay.inventory(files)
        self.context = [f for f in inventory.context if f.name != FEEDBACK_NAME and assay.filled(f)]
        self.titles = {f.name: context_title(f) for f in self.context}
        targets = {Category.ENVIRONMENT: "adaptation.md"}
        self.renames = [(f.name, targets.get(f.category, "core.md")) for f in inventory.core]
        self.renames += [(name, title) for name, title in self.titles.items()]
        self.core = {f.category: Document.read(f, self.rewrite(f.content)) for f in inventory.core}

    def rewrite(self, text: str) -> str:
        """A mention of an intake file by name, as the layer (or note) that now holds its text."""
        for name, target in self.renames:
            text = re.sub(rf"(?<![\w.-]){re.escape(name)}(?![\w-])", target, text)
        return text

    def doc(self, category: Category) -> Document | None:
        return self.core.get(category)


def context_title(file: IntakeFile) -> str:
    first = next((heading(line) for line in file.content.split("\n") if heading(line)), None)
    return first[1] if first and first[0] == 1 else file.name.removesuffix(".md")


def context_note(source: Source, file: IntakeFile) -> list[str]:
    """A Misc Context file as a note under its title, its own headings below it."""
    lines = source.rewrite(file.content).split("\n")
    first = next((i for i, line in enumerate(lines) if line.strip()), None)
    if first is not None and (found := heading(lines[first])) and found[0] == 1:
        lines = lines[first + 1 :]
    levels = [h[0] for h in (heading(line) for line in lines) if h]
    body = shift(lines, max(0, 4 - min(levels))) if levels else lines
    return ["", f"### {source.titles[file.name]}", "", *trim(body)]


# Sections


def core_section(source: Source, title: str) -> list[str]:
    music = source.doc(Category.MUSIC)
    if title == "Reasoning approach":
        return whole(source.doc(Category.PERSON))
    if title == "Execution guidance":
        return whole(source.doc(Category.INSTRUMENT_AWARENESS))
    if music is None:
        return []
    if title == "Purpose":
        return trim([*music.lead, "", *music.body("Purpose")])
    return music.body({"Core principles": "Core Principles", "Value logic": "Value Logic", "Decision rules": "Decision Logic"}[title])


def whole(doc: Document | None) -> list[str]:
    """A file's lead, then every one of its sections."""
    if doc is None:
        return []
    return trim([*doc.lead, "", *combined(doc.parts)]) if doc.parts else doc.lead


def adaptation_section(source: Source, title: str) -> list[str]:
    environment = source.doc(Category.ENVIRONMENT)
    if title == "Operating context":
        notes = [line for f in source.context for line in context_note(source, f)]
        return trim([*(environment.lead if environment else []), *notes])
    if environment is None:
        return []
    if title == "Data sources and mappings":
        return environment.body("Data Layer")
    if title == "Account and industry adjustments":
        return environment.body("Adaptation Layer")
    shown = [p for p in (environment.part("User Experience"), environment.part("Styling")) if p]
    return combined(shown) if shown else []


# A Protection Layer sub-section goes under the section its title names, tested in this order.
PROTECTION_WORDS = (
    ("Security", ("secur", "access", "privacy", "credential", "permission", "confidential")),
    ("Quality controls", ("quality", "performance", "review")),
    ("Validation checks", ("validat", "check", "reconcil", "verif", "test")),
)


def protection_home(title: str) -> str:
    lowered = title.casefold()
    return next((home for home, words in PROTECTION_WORDS if any(word in lowered for word in words)), "Guardrails")


def protection_sections(source: Source) -> dict[str, list[str]]:
    environment = source.doc(Category.ENVIRONMENT)
    found = environment.part("Protection Layer") if environment else None
    homes: dict[str, list[Part]] = {title: [] for title in LAYERS[2].sections}
    intro: list[str] = []
    if found is not None:
        intro, subsections = split(found.lines, 3)
        for part in subsections:
            homes[protection_home(part.title)].append(part)
    bodies = {title: combined(parts) if parts else [] for title, parts in homes.items()}
    bodies["Guardrails"] = trim([*trim(intro), "", *bodies["Guardrails"]])
    return bodies


def learned_rules(prior: list[dict[str, Any]]) -> list[str]:
    """One rule per class of finding iteration 1 raised (advisories aside, D-12), in report order,
    each citing the findings it was learned from."""
    raised = sorted((f for f in prior if not f.get("advisory")), key=lambda f: order(str(f["id"])))
    classes = [c for c in ("Numeric", "Visual", "Latency") if any(f.get("category") == c for f in raised)]
    classes += sorted({str(f.get("category")) for f in raised} - set(classes))
    if not classes:
        return ["Iteration 1 raised no findings, so no rule was learned from it."]
    lines = ["One rule for each class of finding iteration 1 raised. The checks behind each one run on every build."]
    for category in classes:
        cited = [f for f in raised if f.get("category") == category]
        rule = RULES.get(category, f"A {category} finding must not recur: each check that found one in iteration 1 runs again on every build.")
        names = [f"{f['id']} ({'; '.join(f.get('panel_titles') or []) or 'no panel'})" for f in cited]
        lines += ["", f"### {category}", "", rule, "", f"Learned from iteration 1's {listing(names)}."]
    return lines


def listing(items: list[str]) -> str:
    return items[0] if len(items) == 1 else f"{', '.join(items[:-1])} and {items[-1]}"


# The files


def header(seed: str, name: str, iteration: int, fingerprint: str) -> list[str]:
    return [
        f"# {seed}: {name}",
        "",
        f"- Seed: {seed}",
        f"- Iteration: {iteration}",
        f"- Intake fingerprint: {fingerprint}",
        "- Generated by SeedFoundry",
        "",
        description(name, iteration),
    ]


def tidy(lines: list[str]) -> str:
    """One blank line at most between blocks (outside code fences), and one newline at the end."""
    out: list[str] = []
    fenced = False
    for line in lines:
        if _FENCE.match(line):
            fenced = not fenced
        if not fenced and not line.strip() and out and not out[-1].strip():
            continue
        out.append(line.rstrip() if not fenced else line)
    return "\n".join(trim(out)) + "\n"


def drafts(files: list[IntakeFile], seed: str, iteration: int, fingerprint: str, prior: list[dict[str, Any]] | None = None) -> dict[str, str]:
    """The three layers from the intake a build read. `prior` is iteration 1's findings, which
    iteration 2's learned rules come from."""
    source = Source(files)
    protection = protection_sections(source)
    bodies = {
        "core.md": lambda title: core_section(source, title),
        "adaptation.md": lambda title: adaptation_section(source, title),
        "protection.md": lambda title: learned_rules(prior or []) if title == LEARNED_RULES else protection[title],
    }
    out = {}
    for item in LAYERS:
        lines = header(seed, item.name, iteration, fingerprint)
        for title in sections(item.name, iteration):
            lines += ["", f"## {title}", "", *(bodies[item.name](title) or [NOTHING])]
        out[item.name] = tidy(lines)
    return out


def known_issues(findings: list[dict[str, Any]], iteration: int) -> list[str]:
    """The approved build's open findings (advisories aside), one item each (FR-F-4, D-10)."""
    open_ = sorted((f for f in findings if not f.get("advisory")), key=lambda f: order(str(f["id"])))
    count = f"{len(open_)} open finding" + ("" if len(open_) == 1 else "s")
    lines = [f"Approved at iteration {iteration} with {count}. Each stays a known issue until a later build resolves it.", ""]
    for f in open_:
        # The message names the finding's first panel; a finding on several names them all.
        panels = f.get("panel_titles") or []
        where = f" Panels: {'; '.join(panels)}." if len(panels) > 1 else ""
        lines.append(f"- **{f['id']}** ({f.get('category')}, {f.get('severity')}): {f.get('message', '')}. Expected {f.get('expected')}, shown {f.get('shown')}.{where}")
    return lines


def with_known_issues(text: str, findings: list[dict[str, Any]], iteration: int) -> str:
    return tidy([*text.rstrip("\n").split("\n"), "", f"## {KNOWN_ISSUES}", "", *known_issues(findings, iteration)])


# The manifest (T-05)


def manifest(seed: str, iteration: int, fingerprint: str, layers: dict[str, str]) -> dict[str, Any]:
    return {
        "seed": seed,
        "iteration": iteration,
        "fingerprint": fingerprint,
        "generator": "SeedFoundry",
        "layers": [
            {
                "name": item.name,
                "role": item.role,
                "bytes": len(layers[item.name].encode("utf-8")),
                "sha256": hashlib.sha256(layers[item.name].encode("utf-8")).hexdigest(),
                "sections": list(sections(item.name, iteration)),
            }
            for item in LAYERS
        ],
    }


def manifest_problems(document: Any) -> list[str]:
    """What is wrong with a manifest, or nothing (T-05)."""
    if not isinstance(document, dict):
        return ["the manifest is not an object"]
    problems = [f"{field} is missing or empty" for field in ("seed", "fingerprint", "generator") if not document.get(field)]
    if document.get("iteration") not in (1, 2):
        problems.append("iteration is not 1 or 2")
    layers = document.get("layers")
    if not isinstance(layers, list) or [item.get("role") for item in layers if isinstance(item, dict)] != [item.role for item in LAYERS]:
        return problems + ["layers are not core, adaptation and protection in that order"]
    for item in layers:
        if not isinstance(item.get("bytes"), int) or item["bytes"] <= 0:
            problems.append(f"{item.get('name')}: bytes is not a positive number")
        if not isinstance(item.get("sha256"), str) or len(item["sha256"]) != 64:
            problems.append(f"{item.get('name')}: sha256 is not a 64 character digest")
        if not item.get("sections"):
            problems.append(f"{item.get('name')}: no sections")
    return problems
