"""The three Seed layers as outlines: the header block and section headings of
build-simulation.md §7, with no body yet. Synthesis drafts these in M5, so the
manifest, the upload checksums and Planting's heading summary are computed from
real bytes. M11 fills the sections from the distilled intake (FR-F-5).

Known issues are added only on approval of iteration 1 (D-10), which happens after
the build, so no outline has them.
"""

from __future__ import annotations

import hashlib
from typing import Any

LAYERS: tuple[tuple[str, str, tuple[str, ...]], ...] = (
    (
        "core.md",
        "core",
        ("Purpose", "Core principles", "Value logic", "Decision rules", "Reasoning approach", "Execution guidance"),
    ),
    (
        "adaptation.md",
        "adaptation",
        ("Operating context", "Data sources and mappings", "Account and industry adjustments", "Presentation notes"),
    ),
    ("protection.md", "protection", ("Guardrails", "Validation checks", "Quality controls", "Security")),
)

LEARNED_RULES = "Learned rules"  # protection.md, iteration 2 only


def sections(name: str, iteration: int) -> tuple[str, ...]:
    _, role, base = next(layer for layer in LAYERS if layer[0] == name)
    return base + (LEARNED_RULES,) if role == "protection" and iteration == 2 else base


def outline(name: str, seed: str, iteration: int, fingerprint: str) -> str:
    lines = [
        f"# {seed}: {name}",
        "",
        f"- Seed: {seed}",
        f"- Iteration: {iteration}",
        f"- Intake fingerprint: {fingerprint}",
        "- Generated by SeedFoundry",
    ]
    for title in sections(name, iteration):
        lines += ["", f"## {title}"]
    return "\n".join(lines) + "\n"


def manifest(seed: str, iteration: int, fingerprint: str, layers: dict[str, str]) -> dict[str, Any]:
    return {
        "seed": seed,
        "iteration": iteration,
        "fingerprint": fingerprint,
        "generator": "SeedFoundry",
        "layers": [
            {
                "name": name,
                "role": role,
                "bytes": len(layers[name].encode("utf-8")),
                "sha256": hashlib.sha256(layers[name].encode("utf-8")).hexdigest(),
                "sections": list(sections(name, iteration)),
            }
            for name, role, _ in LAYERS
        ],
    }


def manifest_problems(document: Any) -> list[str]:
    """What is wrong with a manifest, or nothing (T-05)."""
    if not isinstance(document, dict):
        return ["the manifest is not an object"]
    problems = [f"{field} is missing or empty" for field in ("seed", "fingerprint", "generator") if not document.get(field)]
    if document.get("iteration") not in (1, 2):
        problems.append("iteration is not 1 or 2")
    layers = document.get("layers")
    if not isinstance(layers, list) or [layer.get("role") for layer in layers if isinstance(layer, dict)] != [r for _, r, _ in LAYERS]:
        return problems + ["layers are not core, adaptation and protection in that order"]
    for layer in layers:
        if not isinstance(layer.get("bytes"), int) or layer["bytes"] <= 0:
            problems.append(f"{layer.get('name')}: bytes is not a positive number")
        if not isinstance(layer.get("sha256"), str) or len(layer["sha256"]) != 64:
            problems.append(f"{layer.get('name')}: sha256 is not a 64 character digest")
        if not layer.get("sections"):
            problems.append(f"{layer.get('name')}: no sections")
    return problems
